name: Build

on:
  push:
    branches:
      - main

env:
  VERSION: "1.0"

jobs:
  build:
    runs-on: [self-hosted, Windows, x64]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Prepare
        run: |
          go mod tidy
          go mod vendor
          go get ./...

      - name: Set version
        shell: bash
        run: |
          echo "$VERSION.$(git rev-parse --short "$GITHUB_SHA")" >> "VERSION"
          cat ./VERSION
          
      - name: Build macOS
        shell: bash
        run: |
          GOOS=darwin GOARCH=amd64 go build -o target/macos/conan-watcher
          chmod +x target/macos/conan-watcher
          cd target/macos
          zip conan-watcher_macOS.zip conan-watcher
          rm -rf conan-watcher

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "conan-watcher_macOS.zip"
          path: "target/macos/conan-watcher_macOS.zip"
